---
# Example blueprints:
# blueprint:
#  - Volume
#  - Machine
# Example subscriptions:
# subscription:
#  - subscription 1
#  - subscription 2
#  - subscription 3
# Example vra workflow Catalog Item
# catalog-item:
#   - source__Sum two numbers
# Example vra workflow Content SOurce
# content-source:
#   - source
# Example Catalog Entitlement:
# catalog-entitlement
#  - content source entitlement 1
#  - content source entitlement 2
# Example Property Groups:
# property-group:
#  - property-group-1
# policy:
#   content-sharing: 
#     - policy name 1
#     - policy name 2

blueprint:
  - Windows (All Editions)
  - Ubuntu Linux
  - Rocky Linux
  - Redhat Enterprise Linux
subscription:
  - Custom Naming - Create Hostname Prefix
  - Active Directory - Add Computer
  - Active Directory - Remove Computer
  - VM - Group Policy Update (Windows)
flavor-mapping:
  - small
  - medium
image-mapping:
  - Redhat Enterprise Linux 8
  - Redhat Enterprise Linux 9
  - RHEL9_NODISK
  - Rocky Linux 8
  - Rocky Linux 9
  - Ubuntu 2204
  - Windows Server 2022
catalog-item: []
custom-resource: []
resource-action: []
catalog-entitlement: []
property-group: []
policy:
  content-sharing:
    - FLC Content
content-source:
  - VM Templates
  - vro